const HomeConstats = {
    NEW_PRODUCT_REQUEST: "NEW_PRODUCT_REQUEST",
    NEW_PRODUCT_SUCCESS: "NEW_PRODUCT_SUCCESS",
    NEW_PRODUCT_FAIL: "NEW_PRODUCT_FAIL",
    NEW_PRODUCT_RESET: "NEW_PRODUCT_RESET",

    ALL_PRODUCT_REQUEST: "ALL_PRODUCT_REQUEST",
    ALL_PRODUCT_SUCCESS: "ALL_PRODUCT_SUCCESS",
    ALL_PRODUCT_FAIL: "ALL_PRODUCT_FAIL",

    ADMIN_PRODUCT_REQUEST: "ADMIN_PRODUCT_REQUEST",
    ADMIN_PRODUCT_SUCCESS: "ADMIN_PRODUCT_SUCCESS",
    ADMIN_PRODUCT_FAIL: "ADMIN_PRODUCT_FAIL",

    DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",
    DELETE_PRODUCT_RESET: "DELETE_PRODUCT_RESET",

    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",
    UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",

    PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",

    ALL_HOMES_REQUEST: "ALL_HOMES_REQUEST",
    ALL_HOMES_SUCCESS: "ALL_HOMES_SUCCESS",
    ALL_HOMES_FAIL: "ALL_HOMES_FAIL",

    UPDATE_STOCK_REQUEST: "UPDATE_STOCK_REQUEST",
    UPDATE_STOCK_SUCCESS: "UPDATE_STOCK_SUCCESS",
    UPDATE_STOCK_FAIL: "UPDATE_STOCK_FAIL",
    UPDATE_STOCK_RESET: "UPDATE_STOCK_RESET",


    // for subAdmin
    NEW_POST_REQUEST: "NEW_POST_REQUEST",
    NEW_POST_SUCCESS: "NEW_POST_SUCCESS",
    NEW_POST_FAIL: "NEW_POST_FAIL",
    NEW_POST_RESET: "NEW_POST_RESET",

    ALL_POST_REQUEST: "ALL_POST_REQUEST",
    ALL_POST_SUCCESS: "ALL_POST_SUCCESS",
    ALL_POST_FAIL: "ALL_POST_FAIL",

    UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
    UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
    UPDATE_POST_FAIL: "UPDATE_POST_FAIL",
    UPDATE_POST_RESET: "UPDATE_POST_RESET",


    // adds & Banner for admin

    ALL_ADDS_REQUEST: "ALL_ADDS_REQUEST",
    ALL_ADDS_SUCCESS: "ALL_ADDS_SUCCESS",
    ALL_ADDS_FAIL: "ALL_ADDS_FAIL",

    NEW_ADDS_REQUEST: "NEW_ADDS_REQUEST",
    NEW_ADDS_SUCCESS: "NEW_ADDS_SUCCESS",
    NEW_ADDS_FAIL: "NEW_ADDS_FAIL",
    NEW_ADDS_RESET: "NEW_ADDS_RESET",

    DELETE_ADDS_REQUEST: "DELETE_ADDS_REQUEST",
    DELETE_ADDS_SUCCESS: "DELETE_ADDS_SUCCESS",
    DELETE_ADDS_FAIL: "DELETE_ADDS_FAIL",
    DELETE_ADDS_RESET: "DELETE_ADDS_RESET",

    ALL_BANNER_REQUEST: "ALL_BANNER_REQUEST",
    ALL_BANNER_SUCCESS: "ALL_BANNER_SUCCESS",
    ALL_BANNER_FAIL: "ALL_BANNER_FAIL",

    NEW_BANNER_REQUEST: "NEW_BANNER_REQUEST",
    NEW_BANNER_SUCCESS: "NEW_BANNER_SUCCESS",
    NEW_BANNER_FAIL: "NEW_BANNER_FAIL",
    NEW_BANNER_RESET: "NEW_BANNER_RESET",

    DELETE_BANNERR_REQUEST: "DELETE_BANNERR_REQUEST",
    DELETE_BANNERR_SUCCESS: "DELETE_BANNERR_SUCCESS",
    DELETE_BANNERR_FAIL: "DELETE_BANNERR_FAIL",
    DELETE_BANNERR_RESET: "DELETE_BANNERR_RESET",

    NEW_REVIEW_REQUEST: "NEW_REVIEW_REQUEST",
    NEW_REVIEW_SUCCESS: "NEW_REVIEW_SUCCESS",
    NEW_REVIEW_FAIL: "NEW_REVIEW_FAIL",
    NEW_REVIEW_RESET: "NEW_REVIEW_RESET",

    ALL_REVIEWS_REQUEST: "ALL_REVIEWS_REQUEST",
    ALL_REVIEWS_SUCCESS: "ALL_REVIEWS_SUCCESS",
    ALL_REVIEWS_FAIL: "ALL_REVIEWS_FAIL",

    DELETE_REVIEW_REQUEST: "DELETE_REVIEW_REQUEST",
    DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
    DELETE_REVIEW_FAIL: "DELETE_REVIEW_FAIL",
    DELETE_REVIEW_RESET: "DELETE_REVIEW_RESET",

    CLEAR_ERRORS: "CLEAR_ERRORS"
}

export default HomeConstats;