const NewsConstants = {
    ALL_NEWS_REQUEST: "ALL_NEWS_REQUEST",
    ALL_NEWS_SUCCESS: "ALL_NEWS_SUCCESS",
    ALL_NEWS_FAIL: "ALL_NEWS_FAIL",

    NEW_NEWS_REQUEST: "NEW_NEWS_REQUEST",
    NEW_NEWS_SUCCESS: "NEW_NEWS_SUCCESS",
    NEW_NEWS_FAIL: "NEW_NEWS_FAIL",
    NEW_NEWS_RESET: "NEW_NEWS_RESET",

    NEWS_DETAILS_REQUEST: "NEWS_DETAILS_REQUEST",
    NEWS_DETAILS_SUCCESS: "NEWS_DETAILS_SUCCESS",
    NEWS_DETAILS_FAIL: "NEWS_DETAILS_FAIL",

    UPDATE_NEWS_REQUEST: "UPDATE_NEWS_REQUEST",
    UPDATE_NEWS_SUCCESS: "UPDATE_NEWS_SUCCESS",
    UPDATE_NEWS_FAIL: "UPDATE_NEWS_FAIL",
    UPDATE_NEWS_RESET: "UPDATE_NEWS_RESET",

    DELETE_NEWS_REQUEST: "DELETE_NEWS_REQUEST",
    DELETE_NEWS_SUCCESS: "DELETE_NEWS_SUCCESS",
    DELETE_NEWS_FAIL: "DELETE_NEWS_FAIL",
    DELETE_NEWS_RESET: "DELETE_NEWS_RESET",


    CLEAR_ERRORS: "CLEAR_ERRORS"
}

export default NewsConstants;