const UserConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
    LOAD_USER_FAIL: "LOAD_USER_FAIL",

    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
    LOGOUT_USER_FAIL: "LOGOUT_USER_FAIL",

    UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAIL: "UPDATE_PROFILE_FAIL",
    UPDATE_PROFILE_RESET: "UPDATE_PROFILE_RESET",

    UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAIL: "UPDATE_PASSWORD_FAIL",
    UPDATE_PASSWORD_RESET: "UPDATE_PASSWORD_RESET",

    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",

    RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAIL: "RESETT_PASSWORD_FAIL",

    ALL_USERS_REQUEST: "ALL_USERS_REQUEST",
    ALL_USERS_SUCCESS: "ALL_USERS_SUCCESS",
    ALL_USERS_FAIL: "ALL_USERS_FAIL",

    ALL_SUBADMIN_REQUEST: "ALL_SUBADMIN_REQUEST",
    ALL_SUBADMIN_SUCCESS: "ALL_SUBADMIN_SUCCESS",
    ALL_SUBADMIN_FAIL: "ALL_SUBADMIN_FAIL",

    USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
    USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
    USER_DETAILS_FAIL: "USER_DETAILS_FAIL",
    USER_DETAILS_RESET: "USER_DETAILS_RESET",

    USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
    USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
    USER_UPDATE_FAIL: "USER_UPDATE_FAIL",
    USER_UPDATE_RESET: "USER_UPDATE_RESET",

    USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
    USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    USER_DELETE_FAIL: "USER_DELETE_FAIL",
    USER_DELETE_RESET: "USER_DELETE_RESET",

    POST_CONTACT_REQUEST: "POST_CONTACT_REQUEST",
    POST_CONTACT_SUCCESS: "POST_CONTACT_SUCCESS",
    POST_CONTACT_FAIL: "POST_CONTACT_SUCCESS",

    CLEAR_ERRORS: "CLEAR_ERRORS"
}

export default UserConstants;